version: "3.9"
services:
  node-red:
    build: node-red
    networks:
      - node_red
    ports:
      - "1880:1880"
    environment:
      SFTP_USER: test
      SFTP_HOST: test
      SFTP_PORT: 22
      SSH_KEY: test
      SFTP_MODULE_PATH: node_modules/@yousolution
      SFTP_SSH_KEY_FILE: key
      SSH_KEY: test

      CUSTOM_DATA_ENDPOINT: custom-data-connector-service
            
      # Miljøvariablen FLOWS fortæller Node-RED IDEet hvilket flow.json den skal åbne og gemme ændringer i ved deploy.
      FLOWS: "/data/flows.json"
      
      # Bind mount fra codespace til den kørende containers /data.
      # Gør det muligt at deploye flowkode direkte fra IDE og bruge git til at comitte ændringerne til repo.
    volumes:
      - "./node-red/:/data" 

networks:
  node_red:
    name: node_red
